export const allItems = [
    {_id: 1, title: "Arts & Crafts"},
    {_id: 2, title: "Automotive"},
    {_id: 3, title: "Baby"},
    {_id: 4, title: "Beauty & Personal Care"},
    {_id: 5, title: "Books"},
    {_id: 6, title: "Boys' Fashion"},
    {_id: 7, title: "Computers"},
    {_id: 8, title: "Deals"},
    {_id: 9, title: "Digital Music"},
    {_id: 10, title: "Electronics"},
    {_id: 11, title: "Girls' Fashion"},
    {_id: 12, title: "Health & Household"},
    {_id: 13, title: "Home & Kitchen"},
    {_id: 14, title: "Industrial & Scientific"},
    {_id: 15, title: "Kindle Store"},
    {_id: 16, title: "Luggage"},
    {_id: 17, title: "Men's Fashion"},
    {_id: 18, title: "Movies & TV"},
    {_id: 19, title: "Music, CDs & Vinyl"},
    {_id: 20, title: "Pet Supplies"},
    {_id: 21, title: "Prime Video"},
    {_id: 22, title: "Software"},
    {_id: 23, title: "Sports & Outdoors"},
    {_id: 24, title: "Tools & Home Improvement"},
    {_id: 25, title: "Toys & Games"},
    {_id: 26, title: "Video Games"},
    {_id: 27, title: "Women's Fashion"},
  ];